import "dotenv/config";
import express, { Request, Response } from "express";
import path from "path";
import fs from "fs";
import { fileURLToPath } from "url";
import { GoogleGenAI } from "@google/genai";
import { createServer as createViteServer } from "vite";
import nodemailer from "nodemailer";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
const PORT = 3000;

app.use(express.json());

// Persistent applications storage
const APPLICATIONS_FILE = path.join(process.cwd(), "applications.json");

// Security & Notification Config
const ADMIN_PIN = process.env.ADMIN_PIN || "8820";
const ADMIN_EMAIL = process.env.ADMIN_EMAIL || "info@croyancegroup.com";

// Admin Authentication Checker
function checkAdminAuth(req: Request): boolean {
  const pinHeader = req.headers["x-admin-pin"] as string | undefined;
  const pinQuery = req.query.pin as string | undefined;
  const provided = pinHeader || pinQuery;
  return Boolean(provided && provided === ADMIN_PIN);
}

// Nodemailer Transporter Helper
function getEmailTransporter() {
  if (process.env.SMTP_HOST && process.env.SMTP_USER && process.env.SMTP_PASS) {
    return nodemailer.createTransport({
      host: process.env.SMTP_HOST,
      port: Number(process.env.SMTP_PORT) || 587,
      secure: Number(process.env.SMTP_PORT) === 465,
      auth: {
        user: process.env.SMTP_USER,
        pass: process.env.SMTP_PASS,
      },
    });
  }
  return null;
}

// Dispatch email notification to admin
async function sendApplicationEmailNotification(
  appData: StoredApplication
): Promise<{ sent: boolean; message: string }> {
  const recipient = ADMIN_EMAIL;
  const transporter = getEmailTransporter();

  const emailSubject = `[New Lease Application] ${appData.referenceNumber} - ${appData.fullName} (${appData.vehicle})`;

  const emailText = `
CROYANCE AUTO LEASE - NEW APPLICATION SUBMISSION
===================================================
Reference ID: ${appData.referenceNumber}
Submitted At: ${new Date(appData.submittedAt).toLocaleString()}

APPLICANT PROFILE:
------------------
Full Name: ${appData.fullName}
Phone Number: ${appData.phoneNumber}
Date of Birth: ${appData.dob || "N/A"}
Residential Address: ${appData.fullAddress}
Marital Status: ${appData.maritalStatus || "N/A"}
Place of Work: ${appData.placeOfWork || "N/A"}
Driving Experience: ${appData.drivingExperience || "N/A"}
Driver's License No: ${appData.licenseNumber || "N/A"}

VEHICLE & FINANCIAL TERMS:
--------------------------
Selected Vehicle: ${appData.vehicle}
30% Deposit Agreement: Ready within 7 business days (${appData.depositAvailable})

ATTACHED DOCUMENTS:
-------------------
• Means of ID: ${appData.meansOfIdFile || "Uploaded on form"}
• Driver's License: ${appData.driversLicenseFile || "Uploaded on form"}
• Utility (NEPA) Bill: ${appData.nepaBillFile || "Uploaded on form"}
• Guarantor's ID: ${appData.guarantorIdFile || "Uploaded on form"}
• Proof of Deposit/Payment: ${appData.proofOfPaymentFile || "Pending allocation"}

---------------------------------------------------
This email notification was automatically generated by the Croyance Auto Lease Underwriting System.
`;

  const emailHtml = `
  <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #E2E5E8; border-radius: 8px; overflow: hidden; background: #ffffff;">
    <div style="background-color: #501087; color: white; padding: 20px; text-align: center;">
      <h2 style="margin: 0; font-size: 20px; letter-spacing: 0.5px;">Croyance Auto Lease Program</h2>
      <p style="margin: 6px 0 0 0; font-size: 13px; color: #19B496; font-weight: bold; text-transform: uppercase;">New Application Underwriting Notification</p>
    </div>
    <div style="padding: 24px;">
      <div style="background-color: #f0dbff; border-left: 4px solid #501087; padding: 12px 16px; margin-bottom: 20px; border-radius: 4px;">
        <p style="margin: 0; font-size: 14px; color: #501087;"><strong>Reference ID:</strong> ${appData.referenceNumber}</p>
        <p style="margin: 4px 0 0 0; font-size: 12px; color: #4A5560;">Submitted: ${new Date(appData.submittedAt).toLocaleString()}</p>
      </div>

      <h3 style="color: #191919; font-size: 15px; border-bottom: 1px solid #E2E5E8; padding-bottom: 6px; margin-top: 0;">Applicant Details</h3>
      <table style="width: 100%; font-size: 13px; margin-bottom: 18px; border-collapse: collapse;">
        <tr><td style="color: #8C96A0; padding: 5px 0; width: 140px;">Full Name:</td><td style="font-weight: bold; color: #191919;">${appData.fullName}</td></tr>
        <tr><td style="color: #8C96A0; padding: 5px 0;">Phone Number:</td><td><a href="tel:${appData.phoneNumber}" style="color: #19B496; font-weight: bold;">${appData.phoneNumber}</a></td></tr>
        <tr><td style="color: #8C96A0; padding: 5px 0;">Residential Address:</td><td style="color: #191919;">${appData.fullAddress}</td></tr>
        <tr><td style="color: #8C96A0; padding: 5px 0;">Place of Work:</td><td style="color: #191919;">${appData.placeOfWork || "N/A"}</td></tr>
        <tr><td style="color: #8C96A0; padding: 5px 0;">Driving Experience:</td><td style="color: #191919;">${appData.drivingExperience || "N/A"}</td></tr>
        <tr><td style="color: #8C96A0; padding: 5px 0;">Driver License No:</td><td style="color: #191919; font-family: monospace;">${appData.licenseNumber || "N/A"}</td></tr>
      </table>

      <h3 style="color: #191919; font-size: 15px; border-bottom: 1px solid #E2E5E8; padding-bottom: 6px;">Vehicle & Terms</h3>
      <table style="width: 100%; font-size: 13px; margin-bottom: 18px; border-collapse: collapse;">
        <tr><td style="color: #8C96A0; padding: 5px 0; width: 140px;">Selected Fleet:</td><td style="font-weight: bold; color: #501087;">${appData.vehicle}</td></tr>
        <tr><td style="color: #8C96A0; padding: 5px 0;">30% Deposit:</td><td style="font-weight: bold; color: #006b58;">Confirmed Ready (Within 7 Business Days)</td></tr>
      </table>

      <div style="background-color: #F5F5F5; border-radius: 6px; padding: 12px; margin-top: 15px;">
        <h4 style="margin: 0 0 8px 0; font-size: 12px; color: #4A5560; text-transform: uppercase;">Attached Proofs</h4>
        <ul style="margin: 0; padding-left: 20px; font-size: 12px; color: #191919; line-height: 1.6;">
          <li>Means of ID: <strong>${appData.meansOfIdFile || "Uploaded"}</strong></li>
          <li>Driver's License: <strong>${appData.driversLicenseFile || "Uploaded"}</strong></li>
          <li>Utility (NEPA) Bill: <strong>${appData.nepaBillFile || "Uploaded"}</strong></li>
          <li>Guarantor's ID: <strong>${appData.guarantorIdFile || "Uploaded"}</strong></li>
        </ul>
      </div>

      <div style="text-align: center; margin-top: 25px;">
        <a href="https://wa.me/${appData.phoneNumber.replace(/[^0-9]/g, "")}" style="display: inline-block; background-color: #25D366; color: white; padding: 11px 22px; border-radius: 6px; text-decoration: none; font-weight: bold; font-size: 13px;">Chat Applicant on WhatsApp (${appData.phoneNumber})</a>
      </div>
    </div>
  </div>
  `;

  if (transporter) {
    try {
      await transporter.sendMail({
        from:
          process.env.SMTP_FROM ||
          `"Croyance Underwriting" <${process.env.SMTP_USER}>`,
        to: recipient,
        subject: emailSubject,
        text: emailText,
        html: emailHtml,
      });
      console.log(`Email successfully dispatched to ${recipient}`);
      return { sent: true, message: `Email delivered to ${recipient}` };
    } catch (err: any) {
      console.error("Failed to send email via SMTP:", err);
      return {
        sent: false,
        message: `SMTP transmission failed: ${err.message}`,
      };
    }
  } else {
    console.log(
      `[Email Notification] Application email prepared for ${recipient}. To send live emails, configure SMTP_HOST, SMTP_USER, and SMTP_PASS.`
    );
    return {
      sent: false,
      message: `Email queued for ${recipient}. (SMTP credentials can be added to .env).`,
    };
  }
}

interface StoredApplication {
  referenceNumber: string;
  submittedAt: string;
  vehicle: string;
  fullName: string;
  dob: string;
  fullAddress: string;
  maritalStatus: string;
  phoneNumber: string;
  placeOfWork: string;
  drivingExperience: string;
  licenseNumber: string;
  depositAvailable: string;
  proofOfPaymentFile?: string | null;
  meansOfIdFile?: string | null;
  driversLicenseFile?: string | null;
  nepaBillFile?: string | null;
  guarantorIdFile?: string | null;
}

function loadApplications(): StoredApplication[] {
  try {
    if (fs.existsSync(APPLICATIONS_FILE)) {
      const raw = fs.readFileSync(APPLICATIONS_FILE, "utf-8");
      return JSON.parse(raw);
    }
  } catch (err) {
    console.error("Failed to read applications.json:", err);
  }
  return [];
}

function saveApplication(newApp: StoredApplication): void {
  try {
    const list = loadApplications();
    list.unshift(newApp);
    fs.writeFileSync(APPLICATIONS_FILE, JSON.stringify(list, null, 2), "utf-8");
  } catch (err) {
    console.error("Failed to save application to applications.json:", err);
  }
}

// Lazy-initialized Gemini client
let aiClient: GoogleGenAI | null = null;
function getAIClient(): GoogleGenAI | null {
  if (!aiClient && process.env.GEMINI_API_KEY) {
    aiClient = new GoogleGenAI({
      apiKey: process.env.GEMINI_API_KEY,
      httpOptions: {
        headers: {
          "User-Agent": "aistudio-build",
        },
      },
    });
  }
  return aiClient;
}

const DOCUMENT_SYSTEM_INSTRUCTION = `You are the official Croyance Auto Lease Virtual Underwriting & Program Assistant for Croyance Group's Car Hire / Lease-to-Own Program in Nigeria.

Your knowledge is STRICTLY constrained to the official Lease-to-Own Program Document and verified page data provided below:

=== OFFICIAL DOCUMENT CONTENT ===
CAR HIRE/LEASE TO OWN PROGRAM
Company: Croyance Group of Companies Limited (Car Purchase / Lease to Own)
Official Website: https://croyancegroup.com/
Head Office Address: 43B, Church Street, Agbelekale Abule-Egba Lagos state Nigeria
Direct Telephone: +2349032360163
WhatsApp Support: 07062343398 (https://wa.me/2347062343398)

Vehicles and Costs Overview:
1. 2005-2006 TOYOTA COROLLA/CAMRY:
   - Registration Cost: ₦120,000
   - Total Cost: ₦10,000,000
   - Deposit Required (30%): ₦3,000,000
   - Monthly Payment (24 Months): ₦300,000
2. 2007-2008 TOYOTA COROLLA:
   - Registration Cost: ₦120,000
   - Total Cost: ₦11,000,000
   - Deposit Required (30%): ₦3,300,000
   - Monthly Payment (24 Months): ₦325,000
3. 2009-2010 TOYOTA COROLLA:
   - Registration Cost: ₦120,000
   - Total Cost: ₦12,000,000
   - Deposit Required (30%): ₦3,600,000
   - Monthly Payment (24 Months): ₦350,000
4. 2011-2013 TOYOTA COROLLA:
   - Registration Cost: ₦120,000
   - Total Cost: ₦13,000,000
   - Deposit Required (30%): ₦3,900,000
   - Monthly Payment (24 Months): ₦380,000

Information Required to Provide (9 items):
1. Full Name
2. Full Address
3. Date of Birth
4. Marital Status
5. Place of Work
6. Driving Experience
7. 30% Down Payment Requirements
8. Proof of Down Payment
9. Driver License Number

Documents to Attach (4 items):
1. Means of ID (NIN, International Passport, or Voter's Card)
2. Driver License (Valid, unexpired FRSC driver's licence)
3. NEPA Bill showing Address (Recent utility bill within 3 months matching residence)
4. Guarantor ID (Valid ID document of a verifiable business or professional guarantor)

Next Steps:
- Confirm your interest in the program.
- Ensure you have the required 30% deposit available within 7 business days.
- Prepare the information and documents for submission.
- Payment period is strictly 24 months. After 24 completed monthly installments, legal ownership and title transfer documents are handed to the applicant.
=== END OF OFFICIAL DOCUMENT CONTENT ===

STRICT ANTI-HALLUCINATION & WHATSAPP RULES:
1. NEVER hallucinate, speculate, guess, or assume answers beyond the explicit facts in this document.
2. CRITICAL USER MANDATE REGARDING WHATSAPP:
   - When you ARE ABLE to answer a question using the official document facts above, give ONLY the direct, clear, factual answer. NEVER display, append, or mention the WhatsApp telephone number if you can answer the question!
   - ONLY display or provide the WhatsApp number (07062343398 / https://wa.me/2347062343398) when you are UNABLE to answer the question, or when the question asks for information not in the document (such as unlisted car models like Mercedes/Honda/Lexus, customized tenure periods like 12 or 36 months, interest rate discounts, zero-deposit waivers, out-of-state deliveries, or private contract alterations), or when the user specifically asks for contact details.
3. When unable to answer, state clearly that the requested information is not in the official program document, and direct them to contact our team on WhatsApp at 07062343398.
4. Maintain a professional, concise, respectful, and authoritative tone suitable for an automotive finance institution.
5. When quoting vehicle prices, deposits, or monthly fees, quote the exact figures from the table.`;

// Document-grounded fallback response generator when API key is missing or offline
function generateDocumentAnswer(userQuery: string): string {
  const query = userQuery.toLowerCase().trim();

  // If question is asking about specific vehicles or costs
  if (
    query.includes("2005") ||
    query.includes("2006") ||
    query.includes("camry")
  ) {
    return `Based on the official Croyance Lease-to-Own document:\n\n**2005–2006 Toyota Corolla/Camry**\n• Registration Cost: ₦120,000\n• Total Cost: ₦10,000,000\n• Deposit Required (30%): ₦3,000,000\n• Monthly Payment (24 Months): ₦300,000\n\nThe required 30% deposit must be available within 7 business days of submitting your application.`;
  }

  if (query.includes("2007") || query.includes("2008")) {
    return `Based on the official Croyance Lease-to-Own document:\n\n**2007–2008 Toyota Corolla**\n• Registration Cost: ₦120,000\n• Total Cost: ₦11,000,000\n• Deposit Required (30%): ₦3,300,000\n• Monthly Payment (24 Months): ₦325,000\n\nThe required 30% deposit must be available within 7 business days.`;
  }

  if (query.includes("2009") || query.includes("2010")) {
    return `Based on the official Croyance Lease-to-Own document:\n\n**2009–2010 Toyota Corolla**\n• Registration Cost: ₦120,000\n• Total Cost: ₦12,000,000\n• Deposit Required (30%): ₦3,600,000\n• Monthly Payment (24 Months): ₦350,000\n\nThe required 30% deposit must be available within 7 business days.`;
  }

  if (
    query.includes("2011") ||
    query.includes("2012") ||
    query.includes("2013")
  ) {
    return `Based on the official Croyance Lease-to-Own document:\n\n**2011–2013 Toyota Corolla**\n• Registration Cost: ₦120,000\n• Total Cost: ₦13,000,000\n• Deposit Required (30%): ₦3,900,000\n• Monthly Payment (24 Months): ₦380,000\n\nThe required 30% deposit must be available within 7 business days.`;
  }

  // Document attachments
  if (
    query.includes("document") ||
    query.includes("attach") ||
    query.includes("requirement") ||
    query.includes("nepa") ||
    query.includes("id") ||
    query.includes("license")
  ) {
    return `According to the official document, here are the required documents to attach:\n1. **Means of ID** (NIN, International Passport, or Voter's Card)\n2. **Driver License** (Valid FRSC license)\n3. **NEPA Bill showing Address** (Recent utility bill within 3 months)\n4. **Guarantor ID**\n\nYou must also provide your Full Name, Full Address, Date of Birth, Marital Status, Place of Work, Driving Experience, and Proof of Down Payment.`;
  }

  // Deposit questions
  if (
    query.includes("deposit") ||
    query.includes("down payment") ||
    query.includes("30%") ||
    query.includes("initial")
  ) {
    return `According to the official document:\n• A **30% deposit** is strictly required to secure your selected vehicle allocation.\n• You must ensure you have this deposit available within **7 business days**.\n• Deposit amounts range from **₦3,000,000** (for 2005-2006 Corolla/Camry) to **₦3,900,000** (for 2011-2013 Corolla).`;
  }

  // Tenure / duration
  if (
    query.includes("period") ||
    query.includes("month") ||
    query.includes("tenure") ||
    query.includes("duration") ||
    query.includes("24") ||
    query.includes("year")
  ) {
    return `According to the official document, the repayment period for all vehicles is fixed at **24 months**.\n\nMonthly payments are:\n• 2005–2006 Corolla/Camry: ₦300,000/mo\n• 2007–2008 Corolla: ₦325,000/mo\n• 2009–2010 Corolla: ₦350,000/mo\n• 2011–2013 Corolla: ₦380,000/mo\n\nFull ownership and title transfer documents are completed after the 24 installments.`;
  }

  // Registration cost
  if (query.includes("registration") || query.includes("reg")) {
    return `According to the official document, the vehicle registration cost is fixed at **₦120,000** for all listed vehicle tiers.`;
  }

  // Office Address
  if (
    query.includes("address") ||
    query.includes("office") ||
    query.includes("location") ||
    query.includes("where")
  ) {
    return `**Croyance Group Head Office Address:**\n43B, Church Street, Agbelekale Abule-Egba Lagos state Nigeria.\n\n• **Direct Telephone:** +2349032360163\n• **Official Homepage:** https://croyancegroup.com/`;
  }

  // Explicit Contact / Telephone Query
  if (
    query.includes("tel") ||
    query.includes("phone") ||
    query.includes("call") ||
    query.includes("whatsapp number") ||
    query.includes("contact number")
  ) {
    return `**Croyance Group Official Contacts:**\n• **Direct Telephone:** +2349032360163\n• **WhatsApp Support:** 07062343398 (https://wa.me/2347062343398)\n• **Head Office Address:** 43B, Church Street, Agbelekale Abule-Egba Lagos state Nigeria\n• **Official Homepage:** https://croyancegroup.com/`;
  }

  // Default: When unable to answer, STRICTLY provide WhatsApp support
  return `This specific question is not answered in the official Croyance Lease-to-Own Program document. To ensure accurate details without assumptions or hallucinations, please contact our support team on WhatsApp for further assistance:\n\n📱 **WhatsApp**: **07062343398**\n🔗 [Click here to chat on WhatsApp](https://wa.me/2347062343398)`;
}

// POST /api/chat
app.post("/api/chat", async (req: Request, res: Response) => {
  try {
    const { messages } = req.body;

    if (!Array.isArray(messages) || messages.length === 0) {
      res.status(400).json({ error: "Missing or invalid 'messages' array" });
      return;
    }

    const latestUserMessage =
      [...messages].reverse().find((m) => m.role === "user")?.content || "";

    const ai = getAIClient();

    if (!ai) {
      // If GEMINI_API_KEY is not configured, reply with grounded document answer
      const answer = generateDocumentAnswer(latestUserMessage);
      res.json({ reply: answer });
      return;
    }

    // Format conversation history for Gemini SDK
    const contents = messages.map((m: { role: string; content: string }) => ({
      role: m.role === "assistant" || m.role === "model" ? "model" : "user",
      parts: [{ text: m.content }],
    }));

    const response = await ai.models.generateContent({
      model: "gemini-3.8-flash",
      contents: contents,
      config: {
        systemInstruction: DOCUMENT_SYSTEM_INSTRUCTION,
        temperature: 0.1, // Low temperature to eliminate hallucination
      },
    });

    const replyText = response.text || generateDocumentAnswer(latestUserMessage);
    res.json({ reply: replyText });
  } catch (error: any) {
    console.error("Gemini API Chat Error:", error);
    // Graceful fallback to document answer with WhatsApp reference when unable to answer
    const latestUserMessage =
      req.body?.messages?.[req.body.messages.length - 1]?.content || "";
    const fallbackAnswer = generateDocumentAnswer(latestUserMessage);
    res.json({ reply: fallbackAnswer });
  }
});

// POST /api/admin/verify - Verify admin pin
app.post("/api/admin/verify", (req: Request, res: Response) => {
  const { pin } = req.body;
  if (pin && pin === ADMIN_PIN) {
    res.json({
      success: true,
      authorized: true,
      adminEmail: ADMIN_EMAIL,
      smtpConfigured: Boolean(
        process.env.SMTP_HOST && process.env.SMTP_USER && process.env.SMTP_PASS
      ),
    });
  } else {
    res.status(401).json({
      success: false,
      authorized: false,
      error: "Invalid Admin PIN. Please check your credentials.",
    });
  }
});

// POST /api/admin/test-email - Test email delivery
app.post("/api/admin/test-email", async (req: Request, res: Response) => {
  if (!checkAdminAuth(req)) {
    res.status(401).json({ error: "Unauthorized access: Valid Admin PIN required" });
    return;
  }

  const dummyApp: StoredApplication = {
    referenceNumber: `TEST-EMAIL-${Date.now().toString().slice(-4)}`,
    submittedAt: new Date().toISOString(),
    vehicle: "2005-2006 Toyota Corolla / Camry (Test Dispatch)",
    fullName: "Croyance Underwriting Test",
    dob: "1990-01-01",
    fullAddress: "43B, Church Street, Agbelekale Abule-Egba Lagos state Nigeria",
    maritalStatus: "Single",
    phoneNumber: "+2349032360163",
    placeOfWork: "Headquarters Test Dept",
    drivingExperience: "5+ Years",
    licenseNumber: "LAG-TEST-001",
    depositAvailable: "Yes",
    meansOfIdFile: "test_nin.pdf",
    driversLicenseFile: "test_license.pdf",
    nepaBillFile: "test_nepa.pdf",
    guarantorIdFile: "test_guarantor.pdf",
  };

  const result = await sendApplicationEmailNotification(dummyApp);
  res.json({
    recipient: ADMIN_EMAIL,
    result,
  });
});

// POST /api/applications - Save submitted application and dispatch email notification
app.post("/api/applications", async (req: Request, res: Response) => {
  try {
    const data = req.body;
    if (!data || !data.fullName || !data.vehicle) {
      res.status(400).json({ error: "Invalid application submission payload" });
      return;
    }

    const newApp: StoredApplication = {
      referenceNumber:
        data.referenceNumber ||
        `CAL-${new Date().getFullYear()}-${Math.floor(
          10000 + Math.random() * 90000
        )}`,
      submittedAt: new Date().toISOString(),
      vehicle: data.vehicle,
      fullName: data.fullName,
      dob: data.dob || "",
      fullAddress: data.fullAddress || "",
      maritalStatus: data.maritalStatus || "",
      phoneNumber: data.phoneNumber || "",
      placeOfWork: data.placeOfWork || "",
      drivingExperience: data.drivingExperience || "",
      licenseNumber: data.licenseNumber || "",
      depositAvailable: data.depositAvailable || "Yes",
      proofOfPaymentFile: data.proofOfPaymentFile || null,
      meansOfIdFile: data.meansOfIdFile || null,
      driversLicenseFile: data.driversLicenseFile || null,
      nepaBillFile: data.nepaBillFile || null,
      guarantorIdFile: data.guarantorIdFile || null,
    };

    saveApplication(newApp);

    // Attempt email notification dispatch to administrator
    const emailResult = await sendApplicationEmailNotification(newApp);

    res.status(201).json({
      success: true,
      message: "Application stored successfully in underwriting database",
      referenceNumber: newApp.referenceNumber,
      emailDispatched: emailResult.sent,
      emailNotice: emailResult.message,
      adminEmail: ADMIN_EMAIL,
      application: newApp,
    });
  } catch (error: any) {
    console.error("Error saving application:", error);
    res.status(500).json({ error: "Failed to store application" });
  }
});

// GET /api/applications - List all submitted applications (Protected by Admin PIN)
app.get("/api/applications", (req: Request, res: Response) => {
  if (!checkAdminAuth(req)) {
    res.status(401).json({
      error: "Unauthorized access: Valid Admin PIN required to inspect submissions",
    });
    return;
  }

  try {
    const apps = loadApplications();
    res.json({
      count: apps.length,
      applications: apps,
      adminEmail: ADMIN_EMAIL,
      smtpConfigured: Boolean(
        process.env.SMTP_HOST && process.env.SMTP_USER && process.env.SMTP_PASS
      ),
    });
  } catch (error: any) {
    res.status(500).json({ error: "Failed to retrieve applications" });
  }
});

// GET /api/applications/export - Download applications as CSV for Excel/Sheets (Protected by Admin PIN)
app.get("/api/applications/export", (req: Request, res: Response) => {
  if (!checkAdminAuth(req)) {
    res.status(401).send(
      "Unauthorized access: Valid Admin PIN required to export submissions. Please use the secure Underwriting Portal."
    );
    return;
  }

  try {
    const apps = loadApplications();
    const headers = [
      "Reference",
      "Submitted At",
      "Vehicle",
      "Full Name",
      "Phone Number",
      "Date of Birth",
      "Address",
      "Place of Work",
      "Driving Experience",
      "License Number",
      "Deposit Ready (30%)",
      "Proof of Payment",
      "Means of ID",
      "Driver License File",
      "NEPA Bill File",
      "Guarantor ID File",
    ];

    const escapeCsv = (val: string | null | undefined) => {
      if (val === null || val === undefined) return '""';
      const clean = String(val).replace(/"/g, '""');
      return `"${clean}"`;
    };

    const rows = apps.map((a) =>
      [
        escapeCsv(a.referenceNumber),
        escapeCsv(a.submittedAt),
        escapeCsv(a.vehicle),
        escapeCsv(a.fullName),
        escapeCsv(a.phoneNumber),
        escapeCsv(a.dob),
        escapeCsv(a.fullAddress),
        escapeCsv(a.placeOfWork),
        escapeCsv(a.drivingExperience),
        escapeCsv(a.licenseNumber),
        escapeCsv(a.depositAvailable),
        escapeCsv(a.proofOfPaymentFile),
        escapeCsv(a.meansOfIdFile),
        escapeCsv(a.driversLicenseFile),
        escapeCsv(a.nepaBillFile),
        escapeCsv(a.guarantorIdFile),
      ].join(",")
    );

    const csvContent = [headers.join(","), ...rows].join("\r\n");

    res.setHeader("Content-Type", "text/csv");
    res.setHeader(
      "Content-Disposition",
      `attachment; filename="croyance-applications-${new Date().toISOString().slice(0, 10)}.csv"`
    );
    res.send(csvContent);
  } catch (error: any) {
    res.status(500).json({ error: "Failed to export applications" });
  }
});

// Start server with Vite middleware in dev or static in production
async function startServer() {
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Croyance Auto Lease server running on http://0.0.0.0:${PORT}`);
  });
}

startServer();
